import type OpenAI from "openai"

import type { Evidence, TokenUsage } from "../types"
import {
  CONTEXT_INTRO,
  CONTEXT_SUFFIX,
  modelTokenCount,
} from "../retrieval/context/assembler"
import {
  formatEvidenceBlock,
  computeContextBudget,
} from "../retrieval/context/budget"

/**
 * Ticket 61 / 04 (spec §2 L1748-1749): result of a successful Evidence-Context
 * compression. The `context` string replaces the deterministic assembler output
 * in the model prompt; all other fields populate the `ContextTraceData` event
 * so callers can report whether compression ran, input/output token counts, and
 * retained/dropped Evidence IDs (spec §2 L1749 acceptance criterion #6).
 */
export interface ContextCompressionResult {
  /**
   * The compressed context string — `CONTEXT_INTRO + compressed blocks + CONTEXT_SUFFIX`.
   * Each compressed block has the deterministic header `[cite:ev_XXX] [来源: SOURCE]\n`
   * (generated by the compressor, NOT the LLM) followed by the LLM-produced
   * compressed content and a trailing newline.
   */
  context: string
  /** Token count of the compressed context (computed with `countTokens`). */
  tokenCount: number
  /**
   * Evidence IDs whose per-group LLM call succeeded and whose compressed
   * blocks are present in `context`. A subset of the input Evidence IDs.
   */
  retainedEvidenceIds: string[]
  /**
   * Evidence IDs whose per-group LLM call failed (empty/invalid/timed-out)
   * and whose compressed blocks are absent from `context`. Present in the
   * input but absent in the output.
   */
  droppedEvidenceIds: string[]
  /** Total uncompressed input token count (overhead + all Evidence blocks). */
  inputTokens: number
  /** Total compressed output token count (`tokenCount` alias for clarity in events). */
  outputTokens: number
  /** Aggregated token usage from all per-group LLM calls (best-effort). */
  usage?: TokenUsage
}

/**
 * Ticket 61 / 04 (spec §2 L1748-1749): LLM-backed Evidence-Context compressor.
 *
 * When the deterministic `ContextAssemblerImpl` output would require truncation
 * or group-dropping to fit the `maxContextTokens` budget (detected via
 * `computeContextBudget(...).overBudget === true`), the compressor compresses
 * each Evidence group independently into a query-relevant block. Each block
 * retains its original Evidence ID, Source identity, and at least one matched
 * passage or extracted fact (spec §2 L1749 acceptance criterion #3). The
 * compressor generates the deterministic header (`[cite:ev_XXX] [来源: SOURCE]\n`)
 * itself — the LLM only produces the compressed content body, so the header
 * is always correct and the LLM cannot create new citation identities or
 * retain an unknown Evidence ID (spec §2 L1749 acceptance criterion #4).
 *
 * Per-group LLM call failures (empty/invalid/timed-out/exception) are
 * swallowed and the group is recorded in `droppedEvidenceIds`. If ALL groups
 * fail, the compressor returns `null` — the caller falls back to the
 * deterministic assembler output (spec §2 L1749 acceptance criterion #5).
 * If the compressed total still exceeds the budget, the compressor also
 * returns `null` — same deterministic fallback.
 *
 * `AbortError` is re-thrown to preserve user-cancellation semantics (same
 * pattern as `triggerSummarization` in Ticket 02 P4 and `ContextualizerImpl`
 * in Ticket 08 P3/P4).
 */
export interface ContextCompressor {
  /**
   * Compress ALL Evidence groups into a single context string.
   *
   * Returns `null` when:
   *   - The uncompressed context fits the budget (bypass — caller should use
   *     the deterministic assembler output as-is, byte-compatible with current
   *     behavior per spec §2 L1748 acceptance criterion #1).
   *   - All per-group LLM calls failed (full discard — deterministic fallback
   *     per spec §2 L1749 acceptance criterion #5).
   *   - The compressed total still exceeds the budget (partial discard is not
   *     enough — deterministic fallback).
   *   - The compressed output contains an unknown Evidence ID (validation
   *     failure — deterministic fallback per spec §2 L1749 acceptance criterion #4).
   *
   * The caller is responsible for:
   *   1. Calling `computeContextBudget` first to decide whether to attempt
   *      compression (the compressor also performs this check internally and
   *      returns `null` when under-budget — defense-in-depth).
   *   2. Using the deterministic assembler output when `compress` returns `null`.
   *   3. Handling `AbortError` (re-thrown by the compressor to preserve
   *      user-cancellation — other errors are swallowed per-group).
   */
  compress(
    evidence: Evidence[],
    query: string,
    budget: {
      maxContextTokens: number
      countTokens?: (text: string) => number
    },
    signal?: AbortSignal
  ): Promise<ContextCompressionResult | null>
}

function extractUsage(res: OpenAI.Chat.Completions.ChatCompletion): TokenUsage | undefined {
  const u = res.usage
  if (!u) return undefined
  return {
    promptTokens: u.prompt_tokens,
    completionTokens: u.completion_tokens ?? 0,
    totalTokens: u.total_tokens,
  }
}

function safeContent(res: OpenAI.Chat.Completions.ChatCompletion): string {
  if (!res.choices || res.choices.length === 0) return ""
  return res.choices[0]?.message?.content || ""
}

function aggregateUsage(usages: (TokenUsage | undefined)[]): TokenUsage | undefined {
  const valid = usages.filter((u): u is TokenUsage => u !== undefined)
  if (valid.length === 0) return undefined
  return valid.reduce((acc, u) => ({
    promptTokens: acc.promptTokens + u.promptTokens,
    completionTokens: acc.completionTokens + u.completionTokens,
    totalTokens: acc.totalTokens + u.totalTokens,
  }))
}

/**
 * Ticket 61 / 04: LLM-backed `ContextCompressor` implementation. Mirrors the
 * `SummarizerImpl`/`ContextualizerImpl` pattern — a single `chat.completions.create`
 * call per Evidence group, with a bounded `max_tokens` (default 200 per group)
 * and Chinese system/user prompts. The LLM only produces the compressed content
 * body; the deterministic header (`[cite:ev_XXX] [来源: SOURCE]\n`) is generated
 * by the compressor itself, so the LLM cannot create new citation identities
 * or corrupt the header format.
 *
 * Groups are compressed in parallel via `Promise.all`. Per-group failures are
 * swallowed (the group is recorded in `droppedEvidenceIds`); `AbortError` is
 * re-thrown to preserve user-cancellation. If all groups fail, or the compressed
 * total still exceeds the budget, or the compressed output contains an unknown
 * Evidence ID, the entire compression is discarded and `null` is returned
 * (deterministic fallback per spec §2 L1749 acceptance criterion #5).
 */
export class ContextCompressorImpl implements ContextCompressor {
  constructor(
    private readonly client: OpenAI,
    private readonly model: string,
    private readonly maxTokensPerGroup: number = 200
  ) {}

  async compress(
    evidence: Evidence[],
    query: string,
    budget: {
      maxContextTokens: number
      countTokens?: (text: string) => number
    },
    signal?: AbortSignal
  ): Promise<ContextCompressionResult | null> {
    const countTokens = budget.countTokens ?? modelTokenCount

    // Step 1: Compute uncompressed token count — bypass when under-budget.
    const breakdown = computeContextBudget(evidence, {
      maxContextTokens: budget.maxContextTokens,
      countTokens,
    })
    if (!breakdown.overBudget) {
      return null // bypass compression — deterministic assembler output is byte-compatible
    }
    const inputTokens = breakdown.uncompressedTokens

    // Step 2: Compress each Evidence group in parallel.
    const groupResults = await Promise.all(
      evidence.map((ev) => this.compressGroup(ev, query, signal))
    )

    const retained: string[] = []
    const dropped: string[] = []
    const blocks: string[] = []
    const usages: (TokenUsage | undefined)[] = []

    for (let i = 0; i < evidence.length; i += 1) {
      const result = groupResults[i]
      if (result !== null) {
        blocks.push(result.block)
        retained.push(evidence[i].id)
        usages.push(result.usage)
      } else {
        dropped.push(evidence[i].id)
      }
    }

    // Step 3: If ALL groups failed, discard compression — deterministic fallback.
    if (blocks.length === 0) {
      return null
    }

    // Step 4: Assemble the compressed context and validate size.
    const context = CONTEXT_INTRO + blocks.join("") + CONTEXT_SUFFIX
    const outputTokens = countTokens(context)
    if (outputTokens > budget.maxContextTokens) {
      return null // still over-budget after compression — deterministic fallback
    }

    // Step 5: Validate no unknown Evidence IDs in the compressed output.
    const knownIds = new Set(evidence.map((ev) => ev.id))
    const citedIds = new Set(
      [...context.matchAll(/\[cite:(ev_[a-f0-9]+)\]/g)].map((m) => m[1])
    )
    for (const id of citedIds) {
      if (!knownIds.has(id)) {
        return null // unknown citation — validation failure — deterministic fallback
      }
    }

    return {
      context,
      tokenCount: outputTokens,
      retainedEvidenceIds: retained,
      droppedEvidenceIds: dropped,
      inputTokens,
      outputTokens,
      usage: aggregateUsage(usages),
    }
  }

  /**
   * Compress a single Evidence group into a block string. Returns `null` on
   * any failure (empty/invalid/timed-out/exception). `AbortError` is re-thrown
   * to preserve user-cancellation; all other errors are swallowed.
   *
   * The returned block has the deterministic header
   * `[cite:ev_XXX] [来源: SOURCE]\n` (generated by this method, NOT the LLM)
   * followed by the LLM-produced compressed content and a trailing newline.
   * The LLM is explicitly instructed NOT to include any citation markers or
   * source headers — only the compressed content body.
   */
  private async compressGroup(
    evidence: Evidence,
    query: string,
    signal?: AbortSignal
  ): Promise<{ block: string; usage?: TokenUsage } | null> {
    try {
      const res = await this.client.chat.completions.create({
        model: this.model,
        max_tokens: this.maxTokensPerGroup,
        messages: [
          {
            role: "system",
            content:
              "你是客服知识库文档压缩器。基于用户问题,把以下文档片段压缩为与问题相关的关键事实块。" +
              "必须保留:至少一条与问题相关的匹配段落或提取事实。" +
              "必须丢弃:与问题无关的内容、重复信息。" +
              "只输出压缩后的内容本身,不要任何前缀、引号、来源标识或证据ID。" +
              "不得输出 [cite:...] 或 [来源: ...] 标记。" +
              "压缩后的内容必须用中文,长度不超过 200 tokens。",
          },
          {
            role: "user",
            content:
              `用户问题:${query}\n\n` +
              `证据ID:${evidence.id}\n` +
              `来源:${evidence.source}\n` +
              `标题:${evidence.title}\n` +
              `文档片段:${evidence.excerpt}\n\n` +
              `请压缩上述文档片段为与用户问题相关的关键事实块。`,
          },
        ],
      }, { signal })
      const content = safeContent(res).trim()
      if (!content) return null
      // Validate: no citation markers in the compressed content (the LLM was
      // instructed not to include them, but we validate defensively per spec
      // §2 L1749 acceptance criterion #4 — "compression cannot create new
      // Citation identities").
      if (/\[cite:[^\]]+\]/.test(content)) return null
      // Generate the deterministic header ourselves — the LLM only produced the
      // compressed content body. This guarantees the header is always correct
      // and the LLM cannot corrupt the citation/source format.
      const header = `[cite:${evidence.id}] [来源: ${evidence.source}]\n`
      return {
        block: `${header}${content}\n`,
        usage: extractUsage(res),
      }
    } catch (err) {
      // AbortError: re-throw to preserve user-cancellation (same pattern as
      // triggerSummarization in Ticket 02 P4 and ContextualizerImpl in P3).
      if (err instanceof Error && err.name === "AbortError") throw err
      // All other errors: swallow and record the group as dropped (deterministic
      // fallback per spec §2 L1749 acceptance criterion #5).
      return null
    }
  }
}
